name: Create New Azure Storage Account

on:
  workflow_dispatch:
    inputs:
      connection_variable_name:
        description: "The env variable name that the app needs to connect to the storage account"
        required: false
      image:
        description: "The container image of the application"
        required: true
      port:
        required: false
        description: "The application port"
      port_payload:
        required: true
        description: >-
          Port's payload, including details for who triggered the action and
          general context (blueprint, run id, etc...)

jobs:
  create-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Inform execution of request to create a new manifest
        id: promote
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_payload).context.runId }}
          logMessage: "Creating a new Azure Storage Account manifest"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create crossplane manifest for s3 bucket
        id: create-manifest
        env:
          BUCKET_FILE_PATH: "storage-reader"
          CROSSPLANE_TEMPLATE_PATH: "crossplane-templates/storage-reader-template.yaml"
        run: |
          mkdir -p $BUCKET_FILE_PATH
          BUCKET_FILE_NAME="${BUCKET_FILE_PATH}/storage-reader-claim.yaml"

          cp $CROSSPLANE_TEMPLATE_PATH $BUCKET_FILE_NAME

          sed -i "s/{{ connection_variable_name }}/${{ inputs.connection_variable_name }}/g" $BUCKET_FILE_NAME
          sed -i "s/{{ image }}/${{ inputs.image }}/g" $BUCKET_FILE_NAME
          sed -i "s/{{ port }}/${{ inputs.port }}/g" $BUCKET_FILE_NAME

          git add $BUCKET_FILE_NAME
            
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.CREATOR_TOKEN }}
          commit-message: Added new storage account reader app with dedicated storage account
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: deployment/${{ fromJson(inputs.port_payload).context.runId }}
          title: "[Deployment] Add new storage account reader app with dedicated storage account"
          body: |
            This PR is automatically generated by Port.
            It contains the crossplane manifest for a new storage account app.

            The manifest is generated based on the blueprint: **${{ fromJson(inputs.port_payload).context.blueprint }}**.

            **Run ID**: ${{ fromJson(inputs.port_payload).context.runId }}.
            **Triggered by**: ${{ fromJson(inputs.port_payload).trigger.by.user.email }}.
            **Triggered at**: ${{ fromJson(inputs.port_payload).trigger.at }}.
            **Triggered from**: ${{ fromJson(inputs.port_payload).trigger.origin }}.


            - Auto-generated by [port-actions][1] 

            [1]: https://app.getport.io/organization/run?runId=${{ fromJson(inputs.port_payload).context.runId }}
          labels: |
            deployment
            automated pr
          assignees: ${{ fromJson(inputs.port_payload).trigger.by.user.email }}

      - name: Inform Port about pull request creation status - Success
        if: steps.create-pr.outputs.pull-request-url != ''
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_payload).context.runId }}
          logMessage: |
            Pull request created successfully. URL: ${{ steps.create-pr.outputs.pull-request-url }}.


      - name: Inform Port about pull request creation status - Failure
        if: steps.create-pr.outputs.pull-request-url == ''
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_payload).context.runId }}
          logMessage: |
            Failed to create pull request. Please check the logs for more details.
